const {test}=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),{chromium}=require('playwright');
test('permission review binds explicit human confirmation to hash, revision and CSRF',async()=>{
 const server=http.createServer((req,res)=>{const name={'/trusted-human/authorization/':'permissions.html','/trusted-human/authorization/permissions.js':'permissions.js','/trusted-human/authorization/permissions.css':'permissions.css'}[req.url.split('?')[0]];if(!name){res.writeHead(404).end();return;}res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync('src/main/resources/ths/'+name));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch();try{
 const page=await browser.newPage(),id='00000000-0000-0000-0000-000000000001',url=`http://127.0.0.1:${server.address().port}/trusted-human/authorization/?proposal=${id}`;
 const card={proposalId:id,revision:0,state:'PENDING',tenant:'ente',proposedBy:'giovanni',reason:'<img src=x onerror=alert(1)>',expiresAt:'2026-09-20T12:00:00Z',proposedHash:'exact-hash',before:null,after:{capabilityId:'ouf.system.status',subjectId:'giovanni',validFrom:'2026-09-20',validUntil:'2026-09-21'}};
 let sent,code=200;
 await page.route('**/api/proposals/**',async route=>{if(route.request().method()==='POST'){sent={body:route.request().postDataJSON(),headers:route.request().headers(),url:route.request().url()};await route.fulfill({status:code,json:{state:sent.url.endsWith('/reject')?'REJECTED':'PUBLISHED',finalPolicyRef:'policy:2'}});}else await route.fulfill({json:{card,csrfHeader:'X-CSRF-TOKEN',csrfToken:'session-csrf'}});});
 await page.goto(url);await page.locator('#review:not([hidden])').waitFor();assert.equal(await page.locator('#reason img').count(),0);assert.equal(await page.locator('#confirm').isDisabled(),true);
 await page.locator('#checked').check();await page.locator('#confirm').click();await page.getByRole('status').filter({hasText:'Modifica pubblicata'}).waitFor();assert.deepEqual(sent.body,{expectedHash:'exact-hash'});assert.equal(sent.headers['if-match'],'"0"');assert.equal(sent.headers['x-csrf-token'],'session-csrf');assert.equal(sent.headers.authorization,undefined);assert.equal(await page.locator('#confirm').isDisabled(),true);
 code=409;await page.goto(url);await page.locator('#review:not([hidden])').waitFor();await page.locator('#checked').check();await page.locator('#confirm').click();await page.getByRole('status').filter({hasText:'Richiedi una nuova proposta'}).waitFor();assert.equal(await page.locator('#confirm').isDisabled(),true);
 code=200;await page.goto(url);await page.locator('#reject:not([disabled])').waitFor();await page.locator('#reject').click();await page.getByRole('status').filter({hasText:'Proposta rifiutata'}).waitFor();assert.equal(sent.url.endsWith('/reject'),true);
 assert.deepEqual(await page.evaluate(()=>[localStorage.length,sessionStorage.length]),[0,0]);fs.mkdirSync('target/browser-evidence',{recursive:true});await page.screenshot({path:'target/browser-evidence/permission-review.png',fullPage:true});
 card.afterRoles={issuer:'https://iam.example',roles:[{roleId:'operator',displayName:'<img src=x onerror=alert(1)>',permissions:[{capabilityId:'ouf.system.status',constraints:{allowedDetailLevels:['PUBLIC_OPERATIONAL']}}]}],assignments:[{roleId:'operator',subjectId:'nominal-person',validFrom:'2026-09-20',validUntil:'2027-09-20'},{roleId:'operator',externalRoleRef:'ente:it',validFrom:'2026-09-20',validUntil:'2027-09-20'}]};
 card.beforeRoles={issuer:'https://iam.example',roles:[],assignments:[]};await page.goto(url);await page.locator('#review:not([hidden])').waitFor();assert.equal(await page.locator('#after img').count(),0);assert.match(await page.locator('#after').textContent(),/nominal-person/);assert.match(await page.locator('#after').textContent(),/ente:it/);assert.match(await page.locator('#after').textContent(),/PUBLIC_OPERATIONAL/);assert.equal(await page.locator('#confirm').isDisabled(),true);
 await page.locator('#checked').check();await page.locator('#confirm').click();await page.getByRole('status').filter({hasText:'Modifica pubblicata'}).waitFor();assert.deepEqual(sent.body,{expectedHash:'exact-hash'});await page.screenshot({path:'target/browser-evidence/role-review.png',fullPage:true});
 await page.unroute('**/api/proposals/**');await page.route('**/api/proposals/**',route=>route.fulfill({status:403,json:{}}));await page.goto(url);await page.getByRole('status').filter({hasText:'Proposta non accessibile'}).waitFor();assert.equal(await page.locator('#review').isHidden(),true);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
});
