package it.comune.trieste.ouf.onboarding;

import static org.assertj.core.api.Assertions.*;
import it.comune.trieste.ouf.onboarding.application.*;
import it.comune.trieste.ouf.onboarding.domain.CanonicalHash;
import java.time.*;import java.util.*;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.test.context.DynamicPropertyRegistry;import org.springframework.test.context.DynamicPropertySource;

@SpringBootTest class IngestionSchedulingRuntimeTest {
  @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->required("OUF_ONB_DB_URL"));r.add("spring.datasource.username",()->required("OUF_ONB_DB_USER"));r.add("spring.datasource.password",()->required("OUF_ONB_DB_PASSWORD"));}
  @Autowired ManagedFileService files;@Autowired OnboardingService onboarding;@Autowired PullSchedulerService scheduler;@Autowired CanonicalHash hashes;@Autowired JdbcClient db;
  OnboardingService.Actor human=new OnboardingService.Actor("human:test","HUMAN_USER");
  @BeforeEach void clean(){db.sql("truncate table ouf_onboarding.audit_event,ouf_onboarding.approval_decision,ouf_onboarding.approval_challenge,ouf_onboarding.pull_dispatch,ouf_onboarding.pull_schedule,ouf_onboarding.managed_file_ingestion,ouf_onboarding.published_configuration,ouf_onboarding.onboarding_version,ouf_onboarding.file_profile,ouf_onboarding.managed_file_asset,ouf_onboarding.source restart identity cascade").update();}

  @Test void managedFileOnboardingCreatesInitialIngestionAndGatesActivation(){byte[] csv="id,name\n1,Alpha\n".getBytes();var asset=files.register(null,"object://staging/managed.csv",hashes.ofBytes(csv),"text/csv",csv.length,"human:test","retention://30d");var profile=files.profile((UUID)asset.get("asset_id"),csv,"object://samples/managed.json");var draft=files.onboard((UUID)asset.get("asset_id"),(UUID)profile.get("profile_id"),"managed-csv","Managed CSV","Comune","https://example.org/Object",List.of("core@1"),human,"c");UUID version=(UUID)draft.get("onboarding_version_id"),ingestion=(UUID)draft.get("initialIngestionId");approve("managed-csv",version);assertThatThrownBy(()->onboarding.activate("managed-csv",version,human,"c")).hasMessageContaining("initial ingestion");var claimed=files.claimIngestion("ingestion-worker",Duration.ofMinutes(1),Instant.now()).orElseThrow();assertThat(claimed.get("ingestion_id")).isEqualTo(ingestion);files.completeIngestion(ingestion,"ingestion-worker","object://curated/managed",1);onboarding.activate("managed-csv",version,human,"c");assertThat(onboarding.version("managed-csv",version).get("state")).isEqualTo("ACTIVE");}

  @Test void pullActivationMaterializesGovernedSchedule(){onboarding.createSource("api","API","EXTERNAL_API","PULL","Comune",Map.of(),human,"c");var draft=onboarding.createVersion("api",configuration("api","PT2M"),human,"c");UUID version=(UUID)draft.get("onboarding_version_id");approve("api",version);onboarding.activate("api",version,human,"c");var schedule=scheduler.schedule("api");assertThat(schedule.get("interval_seconds")).isEqualTo(120);assertThat(schedule.get("timezone")).isEqualTo("Europe/Rome");assertThat(schedule.get("overlap_policy")).isEqualTo("SKIP");}

  @Test void dueScheduleEmitsExactlyOneDispatchAndAdvances(){onboarding.createSource("api","API","EXTERNAL_API","PULL","Comune",Map.of(),human,"c");var draft=onboarding.createVersion("api",configuration("api","PT1M"),human,"c");UUID version=(UUID)draft.get("onboarding_version_id");approve("api",version);onboarding.activate("api",version,human,"c");Instant future=Instant.now().plusSeconds(70);assertThat(scheduler.emitDue(future,10)).hasSize(1);assertThat(scheduler.emitDue(future,10)).isEmpty();assertThat(db.sql("select count(*) from ouf_onboarding.pull_dispatch where source_id='api'").query(Long.class).single()).isEqualTo(1);}

  @Test void pullDispatchSupportsLeaseHeartbeatRetryAndIdempotentCompletion(){onboarding.createSource("api","API","EXTERNAL_API","PULL","Comune",Map.of(),human,"c");var draft=onboarding.createVersion("api",configuration("api","PT1M"),human,"c");UUID version=(UUID)draft.get("onboarding_version_id");approve("api",version);onboarding.activate("api",version,human,"c");Instant now=Instant.now().plusSeconds(70);UUID dispatch=(UUID)scheduler.emitDue(now,10).get(0).get("dispatch_id");var first=scheduler.claim("worker-a",Duration.ofSeconds(30),now).orElseThrow();assertThat(first.get("attempts")).isEqualTo(1);scheduler.heartbeat(dispatch,"worker-a",Duration.ofSeconds(30),now.plusSeconds(1));var retry=scheduler.fail(dispatch,"worker-a","UPSTREAM_TIMEOUT","Timed out",Duration.ZERO);assertThat(retry.get("state")).isEqualTo("RETRY_WAIT");var second=scheduler.claim("worker-b",Duration.ofSeconds(30),now.plusSeconds(2)).orElseThrow();assertThat(second.get("attempts")).isEqualTo(2);var done=scheduler.complete(dispatch,"worker-b","object://curated/api/run-1");assertThat(done.get("state")).isEqualTo("SUCCEEDED");assertThat(scheduler.complete(dispatch,"worker-b","object://curated/api/run-1").get("state")).isEqualTo("SUCCEEDED");}

  @Test void overlapPolicyDoesNotQueueAnotherDispatchWhileOneIsActive(){onboarding.createSource("api","API","EXTERNAL_API","PULL","Comune",Map.of(),human,"c");var draft=onboarding.createVersion("api",configuration("api","PT1M"),human,"c");UUID version=(UUID)draft.get("onboarding_version_id");approve("api",version);onboarding.activate("api",version,human,"c");Instant first=Instant.now().plusSeconds(70);scheduler.emitDue(first,10);scheduler.claim("worker-a",Duration.ofMinutes(5),first).orElseThrow();assertThat(scheduler.emitDue(first.plusSeconds(70),10)).isEmpty();assertThat(db.sql("select count(*) from ouf_onboarding.pull_dispatch where source_id='api'").query(Long.class).single()).isEqualTo(1);}

  @Test void invalidPollIntervalIsRejectedByExecutableValidation(){onboarding.createSource("api","API","EXTERNAL_API","PULL","Comune",Map.of(),human,"c");var draft=onboarding.createVersion("api",configuration("api","PT10S"),human,"c");var result=onboarding.validate("api",(UUID)draft.get("onboarding_version_id"),human,"c");assertThat(result.get("result")).isEqualTo("FAIL");assertThat(result.toString()).contains("ONB_POLL_INTERVAL_INVALID");}

  private void approve(String source,UUID version){onboarding.submit(source,version,0,human,"c");var challenge=onboarding.createChallenge(source,version,human,"c");onboarding.confirm(source,version,(UUID)challenge.get("challenge_id"),human,"c","acr:mfa");}
  private static Map<String,Object> configuration(String source,String interval){return Map.of("syncProfile",Map.of("bootstrap","FULL_SNAPSHOT","incremental","CHANGE_TOKEN","pageSize",500,"pollInterval",interval,"timezone","Europe/Rome","timeoutSeconds",120,"maxAttempts",4),"extractionProfile",Map.of("profileId","ep-"+source,"version","1","sourceId",source,"selection",Map.of("types",List.of("TYPE")),"projection",Map.of("TYPE",List.of("id")),"sync",Map.of("bootstrap","FULL_SNAPSHOT","incremental","CHANGE_TOKEN"),"runtime",Map.of("credentialRef","workload://"+source)),"semanticMapping",Map.of("mappingId","sm-"+source,"sourceType",Map.of("sourceId",source,"typeCode","TYPE"),"targetClasses",List.of(Map.of("classIri","https://example.org/Type")),"semanticRefs",List.of("core@1")),"bundle",Map.of("bundleId","bundle-"+source,"bundleVersion","1.0.0","environment","test","source",Map.of("sourceId",source,"sourceKind","EXTERNAL_API","acquisitionMode","PULL"),"createdFromOnboardingVersion","pending","effectiveFrom","2026-01-01T00:00:00Z","checksum","sha256:pending","status","APPROVED","changeRepresentationProfile",Map.of("mode","FULL_SNAPSHOT")));}
  private static String required(String n){String v=System.getenv(n);if(v==null)throw new IllegalStateException(n+" required");return v;}
}
