package it.comune.trieste.ouf.onboarding.application;

import com.fasterxml.jackson.databind.ObjectMapper;
import it.comune.trieste.ouf.onboarding.domain.*;
import java.sql.Types;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.SqlParameterValue;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;

@Service
public class ManagedFileService {
  private final JdbcClient db; private final ObjectMapper json; private final CanonicalHash hashes; private final ManagedFileProfiler profiler; private final TransactionTemplate tx; private final OnboardingService onboarding;
  public ManagedFileService(JdbcClient db,ObjectMapper json,CanonicalHash hashes,ManagedFileProfiler profiler,TransactionTemplate tx,OnboardingService onboarding){this.db=db;this.json=json;this.hashes=hashes;this.profiler=profiler;this.tx=tx;this.onboarding=onboarding;}
  public Map<String,Object> register(String sourceId,String stagingRef,String contentHash,String mediaType,long size,String uploadedBy,String retentionRef){
    if(!stagingRef.startsWith("object://"))throw invalid("ONB_STAGING_REF_INVALID","stagingRef must use object://");if(size<1||size>52_428_800)throw invalid("ONB_FILE_SIZE_INVALID","File exceeds the 50 MiB intake limit");UUID id=UUID.randomUUID();
    return tx.execute(status->{db.sql("insert into ouf_onboarding.managed_file_asset(asset_id,source_id,staging_ref,content_hash,media_type,size_bytes,uploaded_by,retention_ref) values(:i,:s,:r,:h,:m,:z,:u,:x) on conflict(staging_ref,content_hash) do nothing").param("i",id).param("s",new SqlParameterValue(Types.VARCHAR,sourceId)).param("r",stagingRef).param("h",contentHash).param("m",mediaType).param("z",size).param("u",uploadedBy).param("x",retentionRef).update();return db.sql("select asset_id,source_id,staging_ref,content_hash,media_type,size_bytes,uploaded_by,retention_ref,status,created_at from ouf_onboarding.managed_file_asset where staging_ref=:r and content_hash=:h").param("r",stagingRef).param("h",contentHash).query().singleRow();});
  }
  public Map<String,Object> profile(UUID assetId,byte[] bytes,String sampleRef){
    Map<String,Object> asset=asset(assetId);if(((Number)asset.get("size_bytes")).longValue()!=bytes.length)throw invalid("ONB_FILE_SIZE_MISMATCH","Staged size does not match downloaded content");String actual=hashes.ofBytes(bytes);if(!actual.equals(asset.get("content_hash")))throw invalid("ONB_FILE_HASH_MISMATCH","Staged content hash does not match downloaded content");ManagedFileProfiler.Profile result=profiler.profile(bytes,String.valueOf(asset.get("media_type")));
    return tx.execute(status->{db.sql("select 1 as acquired from pg_advisory_xact_lock(hashtextextended(:i,0))").param("i",assetId.toString()).query(Integer.class).single();int version=db.sql("select coalesce(max(version),0)+1 from ouf_onboarding.file_profile where asset_id=:a").param("a",assetId).query(Integer.class).single();UUID profileId=UUID.randomUUID();db.sql("insert into ouf_onboarding.file_profile(profile_id,asset_id,version,format,metadata,inferred_schema,candidate_keys,sample_ref) values(:i,:a,:v,:f,cast(:m as jsonb),cast(:s as jsonb),cast(:k as jsonb),:r)").param("i",profileId).param("a",assetId).param("v",version).param("f",result.format()).param("m",write(result.metadata())).param("s",write(result.columns())).param("k",write(result.candidateKeys())).param("r",sampleRef).update();db.sql("update ouf_onboarding.managed_file_asset set status='PROFILED' where asset_id=:a and status in ('STAGED','PROFILED')").param("a",assetId).update();return fileProfile(assetId,profileId);});
  }
  public Map<String,Object> asset(UUID id){return db.sql("select asset_id,source_id,staging_ref,content_hash,media_type,size_bytes,uploaded_by,retention_ref,status,created_at from ouf_onboarding.managed_file_asset where asset_id=:i").param("i",id).query().listOfRows().stream().findFirst().orElseThrow(()->new DomainFailure(HttpStatus.NOT_FOUND,"ONB_FILE_ASSET_NOT_FOUND","Managed file asset not found"));}
  public Map<String,Object> fileProfile(UUID asset,UUID profile){return jsonRow(db.sql("select profile_id,asset_id,version,format,metadata::text metadata,inferred_schema::text inferred_schema,candidate_keys::text candidate_keys,sample_ref,created_at from ouf_onboarding.file_profile where asset_id=:a and profile_id=:p").param("a",asset).param("p",profile).query().listOfRows().stream().findFirst().orElseThrow(()->new DomainFailure(HttpStatus.NOT_FOUND,"ONB_FILE_PROFILE_NOT_FOUND","File profile not found")),"metadata","inferred_schema","candidate_keys");}
  public Map<String,Object> onboard(UUID assetId,UUID profileId,String sourceId,String name,String owner,String targetClassIri,List<String> semanticRefs,OnboardingService.Actor actor,String correlation){
    return tx.execute(status->{Map<String,Object> asset=asset(assetId),profile=fileProfile(assetId,profileId);onboarding.createSource(sourceId,name,"INTERNAL_MANAGED","MANAGED",owner,Map.of("managedFileAssetId",assetId.toString(),"contentHash",asset.get("content_hash")),actor,correlation);db.sql("update ouf_onboarding.managed_file_asset set source_id=:s where asset_id=:a and source_id is null").param("s",sourceId).param("a",assetId).update();
      @SuppressWarnings("unchecked") List<Map<String,Object>> columns=(List<Map<String,Object>>)profile.get("inferred_schema");List<String> names=columns.stream().map(c->String.valueOf(c.get("name"))).toList();Map<String,Object> sync=Map.of("bootstrap","FULL_SNAPSHOT","incremental","NONE","executionMode","ONBOARDING_INITIAL_INGESTION","pageSize",500);Map<String,Object> config=new LinkedHashMap<>();config.put("syncProfile",sync);config.put("extractionProfile",Map.of("profileId","file-"+profileId,"version",String.valueOf(profile.get("version")),"sourceId",sourceId,"selection",Map.of("assetId",assetId.toString()),"projection",Map.of("FILE",names),"sync",sync,"runtime",Map.of("mode","MANAGED","stagingRef",asset.get("staging_ref"))));config.put("semanticMapping",Map.of("mappingId","sm-"+sourceId,"sourceType",Map.of("sourceId",sourceId,"typeCode","FILE"),"targetClasses",List.of(Map.of("classIri",targetClassIri)),"semanticRefs",semanticRefs));config.put("bundle",Map.of("bundleId","bundle-"+sourceId,"bundleVersion","1.0.0","environment","managed","source",Map.of("sourceId",sourceId,"sourceKind","INTERNAL_MANAGED","acquisitionMode","MANAGED"),"createdFromOnboardingVersion","pending","effectiveFrom","1970-01-01T00:00:00Z","checksum","sha256:pending","status","APPROVED","changeRepresentationProfile",Map.of("mode","FULL_SNAPSHOT")));Map<String,Object> draft=onboarding.createVersion(sourceId,config,actor,correlation);UUID versionId=(UUID)draft.get("onboarding_version_id"),ingestionId=UUID.randomUUID();db.sql("insert into ouf_onboarding.managed_file_ingestion(ingestion_id,asset_id,profile_id,source_id,onboarding_version_id) values(:i,:a,:p,:s,:v)").param("i",ingestionId).param("a",assetId).param("p",profileId).param("s",sourceId).param("v",versionId).update();Map<String,Object> out=new LinkedHashMap<>(draft);out.put("initialIngestionId",ingestionId);out.put("initialIngestionState","READY");return out;});
  }
  public Map<String,Object> completeIngestion(UUID ingestionId,String worker,String outputRef,long rows){return tx.execute(status->{int changed=db.sql("update ouf_onboarding.managed_file_ingestion set state='SUCCEEDED',claimed_by=null,lease_until=null,output_ref=:o,ingested_rows=:r,completed_at=transaction_timestamp() where ingestion_id=:i and state in ('READY','RUNNING') and (:w=claimed_by or claimed_by is null)").param("o",outputRef).param("r",rows).param("i",ingestionId).param("w",worker).update();if(changed!=1)throw invalid("ONB_FILE_INGESTION_CONFLICT","Initial ingestion is already terminal or owned by another worker");return ingestion(ingestionId);});}
  public Map<String,Object> ingestion(UUID id){return db.sql("select ingestion_id,asset_id,profile_id,source_id,onboarding_version_id,state,output_ref,ingested_rows,error_code,created_at,completed_at from ouf_onboarding.managed_file_ingestion where ingestion_id=:i").param("i",id).query().singleRow();}
  private String write(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalArgumentException(e);}}
  private Map<String,Object> jsonRow(Map<String,Object> row,String...fields){try{Map<String,Object> out=new LinkedHashMap<>(row);for(String f:fields)if(out.get(f) instanceof String s)out.put(f,json.readValue(s,Object.class));return out;}catch(Exception e){throw new IllegalStateException(e);}}
  private static DomainFailure invalid(String code,String message){return new DomainFailure(HttpStatus.UNPROCESSABLE_ENTITY,code,message);}
}
