package it.comune.trieste.ouf.onboarding.application;

import com.fasterxml.jackson.databind.ObjectMapper;
import it.comune.trieste.ouf.onboarding.domain.*;
import java.time.*;
import java.util.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class OnboardingService {
  private final JdbcClient db; private final ObjectMapper json; private final CanonicalHash hashes; private final ConfigurationValidator validator; private final PublishedBundleCompiler bundles;private final RuntimeProjectionService projections;private final SchemaSurveillanceService surveillance; private final Duration challengeTtl;
  public OnboardingService(JdbcClient db,ObjectMapper json,CanonicalHash hashes,ConfigurationValidator validator,PublishedBundleCompiler bundles,RuntimeProjectionService projections,SchemaSurveillanceService surveillance,@Value("${ouf.onboarding.approval-challenge-ttl:PT10M}") Duration challengeTtl){this.db=db;this.json=json;this.hashes=hashes;this.validator=validator;this.bundles=bundles;this.projections=projections;this.surveillance=surveillance;this.challengeTtl=challengeTtl;}

  @Transactional public Map<String,Object> createSource(String id,String name,String kind,String mode,String owner,Map<String,Object> metadata,Actor actor,String correlation){
    if("INTERNAL_MANAGED".equals(kind)&&!"MANAGED".equals(mode))throw bad("ONB_SOURCE_MODE_INVALID","INTERNAL_MANAGED requires MANAGED acquisition");
    db.sql("insert into ouf_onboarding.source(source_id,name,source_kind,acquisition_mode,owner_ref,metadata) values(:i,:n,:k,:m,:o,cast(:x as jsonb))")
      .param("i",id).param("n",name).param("k",kind).param("m",mode).param("o",owner).param("x",write(metadata)).update();
    audit(id,null,correlation,actor,"SOURCE_CREATED",Map.of("sourceKind",kind)); return source(id);
  }
  public Map<String,Object> source(String id){return jsonRow(db.sql("select source_id,name,source_kind,acquisition_mode,status,owner_ref,metadata::text metadata,lock_version,created_at,updated_at from ouf_onboarding.source where source_id=:i").param("i",id).query().listOfRows().stream().findFirst().orElseThrow(()->missing("source")),"metadata");}
  public List<Map<String,Object>> sources(){return db.sql("select source_id,name,source_kind,acquisition_mode,status,owner_ref,metadata::text metadata,lock_version,created_at,updated_at from ouf_onboarding.source order by source_id").query().listOfRows().stream().map(x->jsonRow(x,"metadata")).toList();}
  public List<Map<String,Object>> sources(String after,int limit){if(limit<1||limit>200)throw bad("ONB_PAGE_SIZE_INVALID","limit must be between 1 and 200");return db.sql("select source_id,name,source_kind,acquisition_mode,status,owner_ref,metadata::text metadata,lock_version,created_at,updated_at from ouf_onboarding.source where (:a is null or source_id>:a) order by source_id limit :l").param("a",new org.springframework.jdbc.core.SqlParameterValue(java.sql.Types.VARCHAR,after)).param("l",limit).query().listOfRows().stream().map(x->jsonRow(x,"metadata")).toList();}
  @Transactional public Map<String,Object> updateSource(String id,long expected,String name,String owner,String status,Map<String,Object> metadata,Actor actor,String correlation){Map<String,Object> current=source(id);String nextName=name==null?String.valueOf(current.get("name")):name;String nextOwner=owner==null?String.valueOf(current.get("owner_ref")):owner;String nextStatus=status==null?String.valueOf(current.get("status")):status;Object nextMetadata=metadata==null?current.get("metadata"):metadata;int changed=db.sql("update ouf_onboarding.source set name=:n,owner_ref=:o,status=:t,metadata=cast(:m as jsonb),lock_version=lock_version+1,updated_at=transaction_timestamp() where source_id=:s and lock_version=:l").param("n",nextName).param("o",nextOwner).param("t",nextStatus).param("m",write(nextMetadata)).param("s",id).param("l",expected).update();if(changed!=1)throw precondition();audit(id,null,correlation,actor,"SOURCE_UPDATED",Map.of("expectedLockVersion",expected));return source(id);}

  @Transactional public Map<String,Object> createVersion(String sourceId,Map<String,Object> configuration,Actor actor,String correlation){
    source(sourceId);db.sql("select 1 from (select pg_advisory_xact_lock(hashtextextended(:s,0))) locked").param("s",sourceId).query(Integer.class).single();UUID id=UUID.randomUUID();
    int version=db.sql("select coalesce(max(version),0)+1 from ouf_onboarding.onboarding_version where source_id=:s").param("s",sourceId).query(Integer.class).single();
    db.sql("insert into ouf_onboarding.onboarding_version(onboarding_version_id,source_id,version,state,configuration) values(:i,:s,:v,'DRAFT',cast(:c as jsonb))")
      .param("i",id).param("s",sourceId).param("v",version).param("c",write(configuration)).update();
    audit(sourceId,id,correlation,actor,"ONBOARDING_VERSION_CREATED",Map.of("version",version)); return version(sourceId,id);
  }
  public Map<String,Object> version(String sourceId,UUID id){return jsonRow(db.sql("select onboarding_version_id,source_id,version,state,lock_version,configuration::text configuration,configuration_hash,frozen_at,created_at,updated_at from ouf_onboarding.onboarding_version where source_id=:s and onboarding_version_id=:i").param("s",sourceId).param("i",id).query().listOfRows().stream().findFirst().orElseThrow(()->missing("version")),"configuration");}
  @Transactional public Map<String,Object> cloneVersion(String sourceId,UUID parentId,Actor actor,String correlation){Map<String,Object> parent=version(sourceId,parentId);source(sourceId);db.sql("select 1 from (select pg_advisory_xact_lock(hashtextextended(:s,0))) locked").param("s",sourceId).query(Integer.class).single();int number=db.sql("select coalesce(max(version),0)+1 from ouf_onboarding.onboarding_version where source_id=:s").param("s",sourceId).query(Integer.class).single();UUID id=UUID.randomUUID();db.sql("insert into ouf_onboarding.onboarding_version(onboarding_version_id,source_id,version,state,parent_version_id,configuration) values(:i,:s,:n,'DRAFT',:p,cast(:c as jsonb))").param("i",id).param("s",sourceId).param("n",number).param("p",parentId).param("c",write(parent.get("configuration"))).update();audit(sourceId,id,correlation,actor,"ONBOARDING_VERSION_CLONED",Map.of("parentVersionId",parentId));return version(sourceId,id);}
  public Map<String,Object> diff(String sourceId,UUID id){Map<String,Object> current=version(sourceId,id);Map<String,Object> baseline=db.sql("select configuration::text configuration,onboarding_version_id from ouf_onboarding.onboarding_version where onboarding_version_id=(select coalesce(parent_version_id,(select onboarding_version_id from ouf_onboarding.onboarding_version where source_id=:s and state in ('ACTIVE','SUPERSEDED') and onboarding_version_id<>:i order by version desc limit 1)) from ouf_onboarding.onboarding_version where source_id=:s and onboarding_version_id=:i)").param("s",sourceId).param("i",id).query().listOfRows().stream().findFirst().map(r->jsonRow(r,"configuration")).orElse(Map.of("configuration",Map.of()));@SuppressWarnings("unchecked") Map<String,Object> proposed=(Map<String,Object>)current.get("configuration");@SuppressWarnings("unchecked") Map<String,Object> previous=(Map<String,Object>)baseline.get("configuration");List<String> changed=changedSections(proposed,previous);Map<String,Object> before=new LinkedHashMap<>(),after=new LinkedHashMap<>();for(String key:changed){before.put(key,previous.get(key));after.put(key,proposed.get(key));}Map<String,Object> out=new LinkedHashMap<>();out.put("sourceId",sourceId);out.put("onboardingVersionId",id);out.put("baseVersionId",baseline.get("onboarding_version_id"));out.put("changedSections",changed);out.put("before",before);out.put("after",after);return out;}
  public Map<String,Object> buildExtractionProfile(String sourceId,UUID id){Map<String,Object> current=version(sourceId,id);if(!"DRAFT".equals(current.get("state")))throw invalid("Extraction profile can only be built from DRAFT");@SuppressWarnings("unchecked") Map<String,Object> configuration=(Map<String,Object>)current.get("configuration");Object profile=configuration.get("extractionProfile");if(!(profile instanceof Map<?,?>))throw new DomainFailure(HttpStatus.UNPROCESSABLE_ENTITY,"ONB_EXTRACTION_PROFILE_MISSING","Configuration has no extractionProfile");return Map.of("sourceId",sourceId,"onboardingVersionId",id,"extractionProfile",profile,"configurationHash",hashes.of(configuration));}

  @Transactional public Map<String,Object> patchVersion(String sourceId,UUID id,long expected,Map<String,Object> configuration,Actor actor,String correlation){
    int rows=db.sql("update ouf_onboarding.onboarding_version set configuration=cast(:c as jsonb),lock_version=lock_version+1,updated_at=transaction_timestamp() where source_id=:s and onboarding_version_id=:i and state='DRAFT' and lock_version=:l")
      .param("c",write(configuration)).param("s",sourceId).param("i",id).param("l",expected).update();
    if(rows!=1)throw precondition(); audit(sourceId,id,correlation,actor,"DRAFT_UPDATED",Map.of("expectedLockVersion",expected)); return version(sourceId,id);
  }

  @Transactional public Map<String,Object> submit(String sourceId,UUID id,long expected,Actor actor,String correlation){
    Map<String,Object> current=version(sourceId,id);Map<String,Object> validation=validate(sourceId,id,actor,correlation);if(!"PASS".equals(validation.get("result")))throw new DomainFailure(HttpStatus.UNPROCESSABLE_ENTITY,"ONB_VALIDATION_FAILED","Configuration contains blocking validation errors");String hash=hashes.of(current.get("configuration"));
    int rows=db.sql("update ouf_onboarding.onboarding_version set state='IN_REVIEW',configuration_hash=:h,frozen_at=transaction_timestamp(),lock_version=lock_version+1,updated_at=transaction_timestamp() where source_id=:s and onboarding_version_id=:i and state='DRAFT' and lock_version=:l")
      .param("h",hash).param("s",sourceId).param("i",id).param("l",expected).update();
    if(rows!=1)throw precondition();audit(sourceId,id,correlation,actor,"VERSION_SUBMITTED",Map.of("configurationHash",hash));return version(sourceId,id);
  }

  @Transactional public Map<String,Object> validate(String sourceId,UUID id,Actor actor,String correlation){
    Map<String,Object> current=version(sourceId,id);@SuppressWarnings("unchecked") Map<String,Object> configuration=(Map<String,Object>)current.get("configuration");var result=validator.validate(sourceId,configuration);UUID runId=UUID.randomUUID();String hash=hashes.of(configuration);
    db.sql("insert into ouf_onboarding.validation_run(validation_run_id,onboarding_version_id,source_id,configuration_hash,result,error_count,warning_count,findings,actor_subject,actor_type,correlation_id) values(:i,:v,:s,:h,:r,:e,:w,cast(:f as jsonb),:a,:t,:c)")
      .param("i",runId).param("v",id).param("s",sourceId).param("h",hash).param("r",result.valid()?"PASS":"FAIL").param("e",result.errors()).param("w",result.warnings()).param("f",write(result.findings())).param("a",actor.subject()).param("t",actor.type()).param("c",correlation).update();
    audit(sourceId,id,correlation,actor,"VERSION_VALIDATED",Map.of("validationRunId",runId.toString(),"result",result.valid()?"PASS":"FAIL","errors",result.errors()));
    Map<String,Object> response=new LinkedHashMap<>();response.put("validationRunId",runId);response.put("sourceId",sourceId);response.put("onboardingVersionId",id);response.put("configurationHash",hash);response.put("result",result.valid()?"PASS":"FAIL");response.put("errorCount",result.errors());response.put("warningCount",result.warnings());response.put("findings",result.findings());return response;
  }

  @Transactional public Map<String,Object> createChallenge(String sourceId,UUID versionId,Actor actor,String correlation){
    Map<String,Object> v=version(sourceId,versionId);if(!"IN_REVIEW".equals(v.get("state")))throw invalid("Version must be IN_REVIEW");
    UUID id=UUID.randomUUID();Instant expires=Instant.now().plus(challengeTtl);
    db.sql("insert into ouf_onboarding.approval_challenge(challenge_id,onboarding_version_id,source_id,configuration_hash,status,expires_at) values(:c,:v,:s,:h,'CREATED',:e)")
      .param("c",id).param("v",versionId).param("s",sourceId).param("h",v.get("configuration_hash")).param("e",OffsetDateTime.ofInstant(expires,ZoneOffset.UTC)).update();
    audit(sourceId,versionId,correlation,actor,"APPROVAL_CHALLENGE_CREATED",Map.of("challengeId",id.toString()));
    Map<String,Object> response=new LinkedHashMap<>(db.sql("select challenge_id,onboarding_version_id,source_id,configuration_hash,status,expires_at,created_at from ouf_onboarding.approval_challenge where challenge_id=:i").param("i",id).query().singleRow());response.put("trustedApprovalRef","ths://approval-challenges/"+id);
    @SuppressWarnings("unchecked") var configuration=(Map<String,Object>)v.get("configuration");
    ConfigurationValidator.spatial(configuration).ifPresent(profile->{response.put("spatialDecision",profile);response.put("spatialDecisionFindings",validator.validate(sourceId,configuration).findings().stream().filter(f->f.path().startsWith("/extractionProfile/runtime/udp/spatial")).toList());});return response;
  }

  @Transactional public Map<String,Object> confirm(String sourceId,UUID versionId,UUID challengeId,Actor actor,String correlation,String authenticationContextRef){
    if(!"HUMAN_USER".equals(actor.type()))throw new DomainFailure(HttpStatus.FORBIDDEN,"ONB_HUMAN_APPROVAL_REQUIRED","Approval requires a HUMAN_USER identity");
    Map<String,Object> v=version(sourceId,versionId);
    int challenge=db.sql("update ouf_onboarding.approval_challenge set status='CONFIRMED',confirmed_at=transaction_timestamp() where challenge_id=:c and onboarding_version_id=:v and source_id=:s and status='CREATED' and expires_at>transaction_timestamp() and configuration_hash=:h")
      .param("c",challengeId).param("v",versionId).param("s",sourceId).param("h",v.get("configuration_hash")).update();
    if(challenge!=1)throw new DomainFailure(HttpStatus.CONFLICT,"ONB_APPROVAL_CHALLENGE_STALE","Challenge expired, stale, or already consumed");
    int changed=db.sql("update ouf_onboarding.onboarding_version set state='APPROVED',lock_version=lock_version+1,updated_at=transaction_timestamp() where onboarding_version_id=:v and source_id=:s and state='IN_REVIEW'")
      .param("v",versionId).param("s",sourceId).update();if(changed!=1)throw invalid("Version must be IN_REVIEW");
    db.sql("insert into ouf_onboarding.approval_decision(decision_id,challenge_id,onboarding_version_id,actor_subject,decision,target_hash,authentication_context_ref) values(:d,:c,:v,:a,'APPROVE',:h,:x)")
      .param("d",UUID.randomUUID()).param("c",challengeId).param("v",versionId).param("a",actor.subject()).param("h",v.get("configuration_hash")).param("x",authenticationContextRef).update();
    audit(sourceId,versionId,correlation,actor,"VERSION_APPROVED",Map.of("challengeId",challengeId.toString()));return version(sourceId,versionId);
  }

  @Transactional public Map<String,Object> activate(String sourceId,UUID versionId,Actor actor,String correlation){
    if(!"HUMAN_USER".equals(actor.type()))throw new DomainFailure(HttpStatus.FORBIDDEN,"ONB_HUMAN_ACTIVATION_REQUIRED","Activation requires a HUMAN_USER identity");
    surveillance.assertActivationAllowed(sourceId);
    Map<String,Object> v=version(sourceId,versionId);if(!"APPROVED".equals(v.get("state")))throw invalid("Version must be APPROVED");
    boolean compatible=db.sql("select compatible from ouf_onboarding.consumer_compatibility_attestation where onboarding_version_id=:v and consumer='INGESTION_RUNTIME' and configuration_hash=:h order by created_at desc,attestation_id desc limit 1").param("v",versionId).param("h",v.get("configuration_hash")).query(Boolean.class).optional().orElse(false);if(!compatible)throw new DomainFailure(HttpStatus.CONFLICT,"ONB_INGESTION_COMPAT_REQUIRED","Ingestion Runtime must accept the frozen configuration before activation");
    @SuppressWarnings("unchecked") Map<String,Object> configuration=(Map<String,Object>)v.get("configuration");Map<String,Object> bundle=bundles.compile(sourceId,versionId,v.get("version"),String.valueOf(v.get("configuration_hash")),configuration);String checksum=String.valueOf(bundle.get("checksum"));
    db.sql("update ouf_onboarding.published_configuration set active=false where source_id=:s and active=true").param("s",sourceId).update();
    db.sql("update ouf_onboarding.onboarding_version set state='SUPERSEDED',lock_version=lock_version+1,updated_at=transaction_timestamp() where source_id=:s and state='ACTIVE'").param("s",sourceId).update();
    UUID publicationId=UUID.randomUUID();db.sql("insert into ouf_onboarding.published_configuration(publication_id,source_id,onboarding_version_id,bundle_version,bundle,checksum,active,effective_from) values(:p,:s,:v,:n,cast(:b as jsonb),:h,true,transaction_timestamp())")
      .param("p",publicationId).param("s",sourceId).param("v",versionId).param("n",v.get("version")).param("b",write(bundle)).param("h",checksum).update();projections.publish(publicationId,bundle);
    db.sql("update ouf_onboarding.onboarding_version set state='ACTIVE',lock_version=lock_version+1,updated_at=transaction_timestamp() where onboarding_version_id=:v and state='APPROVED'").param("v",versionId).update();
    audit(sourceId,versionId,correlation,actor,"VERSION_ACTIVATED",Map.of("checksum",checksum));return activeBundle(sourceId);
  }
  @Transactional public Map<String,Object> attestIngestionCompatibility(String sourceId,UUID versionId,boolean compatible,String detail,Actor actor,String correlation){
    if(!"SERVICE".equals(actor.type())||!actor.capabilities().contains("ouf.ingestion.configuration.attest"))throw new DomainFailure(HttpStatus.FORBIDDEN,"ONB_INGESTION_ATTESTATION_AUTHORITY_REQUIRED","Compatibility attestation requires the Authorization-owned Ingestion Runtime capability");Map<String,Object> v=version(sourceId,versionId);if(!Set.of("IN_REVIEW","APPROVED").contains(String.valueOf(v.get("state"))))throw invalid("Compatibility may be attested only for a frozen version");UUID id=UUID.randomUUID();db.sql("insert into ouf_onboarding.consumer_compatibility_attestation(attestation_id,onboarding_version_id,consumer,configuration_hash,compatible,detail,actor_subject) values(:i,:v,'INGESTION_RUNTIME',:h,:c,:d,:a)").param("i",id).param("v",versionId).param("h",v.get("configuration_hash")).param("c",compatible).param("d",detail).param("a",actor.subject()).update();audit(sourceId,versionId,correlation,actor,"INGESTION_COMPAT_ATTESTED",Map.of("compatible",compatible));return db.sql("select attestation_id,onboarding_version_id,consumer,configuration_hash,compatible,detail,actor_subject,created_at from ouf_onboarding.consumer_compatibility_attestation where attestation_id=:i").param("i",id).query().singleRow();
  }
  public Map<String,Object> activeBundle(String sourceId){return jsonRow(db.sql("select publication_id,source_id,onboarding_version_id,bundle_version,bundle::text bundle,checksum,effective_from from ouf_onboarding.published_configuration where source_id=:s and active=true").param("s",sourceId).query().listOfRows().stream().findFirst().orElseThrow(()->missing("active bundle")),"bundle");}
  public Map<String,Object> historicalBundle(String sourceId,UUID versionId){return jsonRow(db.sql("select publication_id,source_id,onboarding_version_id,bundle_version,bundle::text bundle,checksum,effective_from,active,created_at from ouf_onboarding.published_configuration where source_id=:s and onboarding_version_id=:v").param("s",sourceId).param("v",versionId).query().listOfRows().stream().findFirst().orElseThrow(()->missing("historical bundle")),"bundle");}
  public List<Map<String,Object>> bundleHistory(String sourceId){return db.sql("select publication_id,source_id,onboarding_version_id,bundle_version,checksum,effective_from,active,created_at from ouf_onboarding.published_configuration where source_id=:s order by bundle_version desc").param("s",sourceId).query().listOfRows();}

  public Map<String,Object> approvalCard(UUID challengeId){Map<String,Object> row=jsonRow(db.sql("select c.challenge_id,c.source_id,c.onboarding_version_id,c.configuration_hash,c.status,c.expires_at,c.created_at,v.version,v.configuration::text configuration,s.name source_name from ouf_onboarding.approval_challenge c join ouf_onboarding.onboarding_version v on v.onboarding_version_id=c.onboarding_version_id join ouf_onboarding.source s on s.source_id=c.source_id where c.challenge_id=:i").param("i",challengeId).query().listOfRows().stream().findFirst().orElseThrow(()->missing("approval challenge")),"configuration");Map<String,Object> out=new LinkedHashMap<>(row);out.put("trustedApprovalRef","ths://approval-challenges/"+challengeId);out.put("changedSections",changedSections((Map<String,Object>)row.get("configuration"),latestConfigurationBefore(String.valueOf(row.get("source_id")),((Number)row.get("version")).intValue())));return out;}
  @Transactional public Map<String,Object> reject(String sourceId,UUID versionId,UUID challengeId,Actor actor,String correlation,String authenticationContextRef){if(!"HUMAN_USER".equals(actor.type()))throw new DomainFailure(HttpStatus.FORBIDDEN,"ONB_HUMAN_APPROVAL_REQUIRED","Rejection requires a HUMAN_USER identity");Map<String,Object> v=version(sourceId,versionId);int challenge=db.sql("update ouf_onboarding.approval_challenge set status='CANCELLED' where challenge_id=:c and onboarding_version_id=:v and source_id=:s and status='CREATED' and expires_at>transaction_timestamp() and configuration_hash=:h").param("c",challengeId).param("v",versionId).param("s",sourceId).param("h",v.get("configuration_hash")).update();if(challenge!=1)throw new DomainFailure(HttpStatus.CONFLICT,"ONB_APPROVAL_CHALLENGE_STALE","Challenge expired, stale, or already consumed");db.sql("update ouf_onboarding.onboarding_version set state='REJECTED',lock_version=lock_version+1,updated_at=transaction_timestamp() where onboarding_version_id=:v and state='IN_REVIEW'").param("v",versionId).update();db.sql("insert into ouf_onboarding.approval_decision(decision_id,challenge_id,onboarding_version_id,actor_subject,decision,target_hash,authentication_context_ref) values(:d,:c,:v,:a,'REJECT',:h,:x)").param("d",UUID.randomUUID()).param("c",challengeId).param("v",versionId).param("a",actor.subject()).param("h",v.get("configuration_hash")).param("x",authenticationContextRef).update();audit(sourceId,versionId,correlation,actor,"VERSION_REJECTED",Map.of("challengeId",challengeId.toString()));return version(sourceId,versionId);}

  private void audit(String source,UUID version,String correlation,Actor actor,String event,Object payload){db.sql("insert into ouf_onboarding.audit_event(audit_event_id,source_id,onboarding_version_id,correlation_id,actor_subject,actor_type,event_type,payload_summary) values(:i,:s,:v,:c,:a,:t,:e,cast(:p as jsonb))").param("i",UUID.randomUUID()).param("s",source).param("v",version).param("c",correlation).param("a",actor.subject()).param("t",actor.type()).param("e",event).param("p",write(payload)).update();}
  private String write(Object value){try{return json.writeValueAsString(value==null?Map.of():value);}catch(Exception e){throw bad("ONB_JSON_INVALID",e.getMessage());}}
  private Map<String,Object> latestConfigurationBefore(String sourceId,int version){return db.sql("select configuration::text configuration from ouf_onboarding.onboarding_version where source_id=:s and version<:v and state in ('ACTIVE','SUPERSEDED') order by version desc limit 1").param("s",sourceId).param("v",version).query().listOfRows().stream().findFirst().map(r->jsonRow(r,"configuration")).map(r->(Map<String,Object>)r.get("configuration")).orElse(Map.of());}
  private static List<String> changedSections(Map<String,Object> proposed,Map<String,Object> previous){Set<String> keys=new TreeSet<>();keys.addAll(proposed.keySet());keys.addAll(previous.keySet());return keys.stream().filter(k->!Objects.equals(proposed.get(k),previous.get(k))).toList();}
  @SuppressWarnings("unchecked") private Map<String,Object> jsonRow(Map<String,Object> row,String field){try{Map<String,Object> out=new LinkedHashMap<>(row);Object value=out.get(field);if(value instanceof String s)out.put(field,json.readValue(s,Object.class));return out;}catch(Exception e){throw new IllegalStateException("database JSON decode failure",e);}}
  private static DomainFailure missing(String what){return new DomainFailure(HttpStatus.NOT_FOUND,"ONB_NOT_FOUND",what+" not found");}
  private static DomainFailure invalid(String message){return new DomainFailure(HttpStatus.UNPROCESSABLE_ENTITY,"ONB_INVALID_STATE_TRANSITION",message);}
  private static DomainFailure bad(String code,String message){return new DomainFailure(HttpStatus.BAD_REQUEST,code,message);}
  private static DomainFailure precondition(){return new DomainFailure(HttpStatus.PRECONDITION_FAILED,"ONB_ETAG_MISMATCH","Stale ETag or immutable version");}
  public record Actor(String subject,String type,Set<String> capabilities){public Actor(String subject,String type){this(subject,type,Set.of());}public Actor{capabilities=capabilities==null?Set.of():Set.copyOf(capabilities);}}
}
