package it.comune.trieste.ouf.onboarding.application;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import it.comune.trieste.ouf.onboarding.domain.*;
import java.nio.charset.StandardCharsets;
import java.time.*;
import java.util.*;
import java.util.stream.Collectors;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;

@Service
public class ProtectedLogService {
  public static final int MAX_RESULTS=200;private static final Duration MAX_WINDOW=Duration.ofDays(31);private static final Set<String> DIMENSIONS=Set.of("service","severity","eventType","actorType");
  public record Search(OffsetDateTime from,OffsetDateTime to,String service,String severity,String correlationId,String eventType,Integer limit,String cursor,String purpose){}
  public record Correlation(String key,String value,OffsetDateTime from,OffsetDateTime to,Integer limit,String purpose){}
  private final JdbcClient db;private final ObjectMapper json;private final CanonicalHash hashes;private final List<ProtectedLogStoreAdapter> stores;private final ProtectedLogAuthorizationGuard guard;private final ProtectedLogRedactionService redaction;private final TransactionTemplate tx;
  public ProtectedLogService(JdbcClient db,ObjectMapper json,CanonicalHash hashes,List<ProtectedLogStoreAdapter> stores,ProtectedLogAuthorizationGuard guard,ProtectedLogRedactionService redaction,TransactionTemplate tx){this.db=db;this.json=json;this.hashes=hashes;this.stores=stores;this.guard=guard;this.redaction=redaction;this.tx=tx;}

  public Map<String,Object> search(Search request,OnboardingService.Actor actor,String auth,String correlation){authorize(actor,"ouf.ths.log.read",request.purpose(),auth,"SEARCH",scope(request),correlation);List<Map<String,Object>> rows=run(request,actor.capabilities().contains("ouf.ths.log.pii.read"));String next=rows.size()>limit(request)?cursor(rows.get(limit(request)-1)):null;if(next!=null)rows=rows.subList(0,limit(request));audit(actor,"SEARCH",request.purpose(),scope(request),rows.size(),auth,"ALLOWED",correlation);return Map.of("items",rows,"resultCount",rows.size(),"nextCursor",next==null?"":next,"redacted",!actor.capabilities().contains("ouf.ths.log.pii.read"));}
  public Map<String,Object> read(String logRef,String purpose,OnboardingService.Actor actor,String auth,String correlation){Map<String,Object> scope=Map.of("logRef",safe(logRef));authorize(actor,"ouf.ths.log.read.detail",purpose,auth,"READ",scope,correlation);Map<String,Object> found=stores.stream().map(s->s.read(logRef)).flatMap(Optional::stream).findFirst().orElseThrow(()->new DomainFailure(HttpStatus.NOT_FOUND,"THS_LOG_NOT_FOUND","Protected log event not found"));Map<String,Object> out=redaction.redact(found,actor.capabilities().contains("ouf.ths.log.pii.read"));audit(actor,"READ",purpose,scope,1,auth,"ALLOWED",correlation);return out;}
  public Map<String,Object> aggregate(Search request,String dimension,OnboardingService.Actor actor,String auth,String correlation){if(!DIMENSIONS.contains(dimension))throw invalid("THS_LOG_DIMENSION_INVALID","Unsupported aggregate dimension");Map<String,Object> scope=new LinkedHashMap<>(scope(request));scope.put("dimension",dimension);authorize(actor,"ouf.ths.log.aggregate",request.purpose(),auth,"AGGREGATE",scope,correlation);List<Map<String,Object>> rows=run(new Search(request.from(),request.to(),request.service(),request.severity(),request.correlationId(),request.eventType(),MAX_RESULTS,null,request.purpose()),false);Map<String,Long> counts=rows.stream().collect(Collectors.groupingBy(r->String.valueOf(r.getOrDefault(dimension,"UNKNOWN")),TreeMap::new,Collectors.counting()));List<Map<String,Object>> buckets=counts.entrySet().stream().limit(100).map(e->Map.<String,Object>of("key",e.getKey(),"count",e.getValue())).toList();audit(actor,"AGGREGATE",request.purpose(),scope,rows.size(),auth,"ALLOWED",correlation);return Map.of("dimension",dimension,"buckets",buckets,"sourceCount",rows.size());}
  public Map<String,Object> correlate(Correlation request,OnboardingService.Actor actor,String auth,String correlation){if(!"correlationId".equals(request.key()))throw invalid("THS_LOG_CORRELATION_KEY_INVALID","Only the predefined correlationId join is currently supported");Search search=new Search(request.from(),request.to(),null,null,request.value(),null,request.limit(),null,request.purpose());Map<String,Object> scope=Map.of("key","correlationId","value",safe(request.value()),"from",request.from().toString(),"to",request.to().toString());authorize(actor,"ouf.ths.log.correlate",request.purpose(),auth,"CORRELATE",scope,correlation);List<Map<String,Object>> rows=run(search,actor.capabilities().contains("ouf.ths.log.pii.read"));audit(actor,"CORRELATE",request.purpose(),scope,rows.size(),auth,"ALLOWED",correlation);return Map.of("correlationKey","correlationId","correlationValue",request.value(),"items",rows,"resultCount",rows.size());}

  public Map<String,Object> createExport(Search request,OnboardingService.Actor actor,String auth,String correlation){Map<String,Object> scope=scope(request);authorize(actor,"ouf.ths.log.export",request.purpose(),auth,"EXPORT_CREATE",scope,correlation);UUID id=UUID.randomUUID();db.sql("insert into ouf_onboarding.protected_log_export_job(export_id,requested_by,purpose,authorization_context_ref,request_scope) values(:i,:a,:p,:x,cast(:s as jsonb))").param("i",id).param("a",actor.subject()).param("p",request.purpose()).param("x",auth).param("s",write(scope)).update();audit(actor,"EXPORT_CREATE",request.purpose(),scope,0,auth,"ALLOWED",correlation);return export(id);}
  public Map<String,Object> export(UUID id,String purpose,OnboardingService.Actor actor,String auth,String correlation){authorize(actor,"ouf.ths.log.export.read",purpose,auth,"EXPORT_READ",Map.of("exportId",id),correlation);Map<String,Object> out=exportForActor(id,actor);audit(actor,"EXPORT_READ",purpose,Map.of("exportId",id),0,auth,"ALLOWED",correlation);return out;}
  public byte[] download(UUID id,String purpose,OnboardingService.Actor actor,String auth,String correlation){authorize(actor,"ouf.ths.log.download",purpose,auth,"DOWNLOAD",Map.of("exportId",id),correlation);Map<String,Object> row=rawExport(id);if(!actor.subject().equals(row.get("requested_by"))&&!actor.capabilities().contains("ouf.ths.log.download.any"))throw new DomainFailure(HttpStatus.FORBIDDEN,"THS_LOG_EXPORT_OWNER_REQUIRED","Export belongs to another operator");if(!"SUCCEEDED".equals(row.get("state"))||row.get("expires_at")==null||((OffsetDateTime)row.get("expires_at")).isBefore(OffsetDateTime.now(ZoneOffset.UTC)))throw new DomainFailure(HttpStatus.CONFLICT,"THS_LOG_EXPORT_NOT_READY","Export is not ready or has expired");byte[] bytes=String.valueOf(row.get("artifact")).getBytes(StandardCharsets.UTF_8);audit(actor,"DOWNLOAD",purpose,Map.of("exportId",id),((Number)row.get("record_count")).intValue(),auth,"ALLOWED",correlation);return bytes;}

  public Optional<Map<String,Object>> claimExport(String worker,Duration lease,Instant now){return tx.execute(status->{OffsetDateTime n=utc(now);db.sql("update ouf_onboarding.protected_log_export_job set state='FAILED',claimed_by=null,lease_until=null,error_code='THS_EXPORT_LEASE_EXHAUSTED',completed_at=:n,updated_at=:n where state='RUNNING' and lease_until<=:n and attempts>=5").param("n",n).update();return db.sql("with candidate as (select export_id from ouf_onboarding.protected_log_export_job where ((state in ('READY','RETRY_WAIT') and next_attempt_at<=:n) or (state='RUNNING' and lease_until<=:n)) and attempts<5 order by created_at for update skip locked limit 1) update ouf_onboarding.protected_log_export_job j set state='RUNNING',claimed_by=:w,lease_until=:u,attempts=attempts+1,updated_at=:n where export_id=(select export_id from candidate) returning j.*").param("n",n).param("w",worker).param("u",utc(now.plus(lease))).query().listOfRows().stream().findFirst();});}
  public void completeExport(Map<String,Object> job,String worker,Duration retention){UUID id=(UUID)job.get("export_id");try{Map<String,Object> scope=readMap(job.get("request_scope"));Search request=fromScope(scope,String.valueOf(job.get("purpose")));List<Map<String,Object>> rows=run(request,false);String artifact=write(Map.of("exportId",id,"generatedAt",OffsetDateTime.now(ZoneOffset.UTC).toString(),"items",rows));String checksum=hashes.ofBytes(artifact.getBytes(StandardCharsets.UTF_8));int changed=db.sql("update ouf_onboarding.protected_log_export_job set state='SUCCEEDED',claimed_by=null,lease_until=null,record_count=:n,result_ref=:r,checksum=:h,artifact=cast(:a as jsonb),expires_at=transaction_timestamp()+make_interval(secs=>:x),completed_at=transaction_timestamp(),updated_at=transaction_timestamp() where export_id=:i and state='RUNNING' and claimed_by=:w and lease_until>transaction_timestamp()").param("n",rows.size()).param("r","protected-export://"+id).param("h",checksum).param("a",artifact).param("x",retention.toSeconds()).param("i",id).param("w",worker).update();if(changed!=1)throw new IllegalStateException("export lease lost");}catch(Exception failure){db.sql("update ouf_onboarding.protected_log_export_job set state=case when attempts>=5 then 'FAILED' else 'RETRY_WAIT' end,claimed_by=null,lease_until=null,next_attempt_at=transaction_timestamp()+interval '30 seconds',error_code='THS_LOG_EXPORT_FAILED',updated_at=transaction_timestamp(),completed_at=case when attempts>=5 then transaction_timestamp() else null end where export_id=:i and state='RUNNING' and claimed_by=:w").param("i",id).param("w",worker).update();}}

  private List<Map<String,Object>> run(Search request,boolean personal){validate(request);int wanted=Math.min(MAX_RESULTS,limit(request)+1);OffsetDateTime upper=cursorTime(request.cursor()).map(c->c.isBefore(request.to())?c:request.to()).orElse(request.to());ProtectedLogStoreAdapter.Query query=new ProtectedLogStoreAdapter.Query(request.from(),upper,blank(request.service()),blank(request.severity()),blank(request.correlationId()),blank(request.eventType()),wanted);return stores.stream().flatMap(s->s.search(query).stream()).sorted(Comparator.comparing(r->OffsetDateTime.parse(String.valueOf(r.get("timestamp"))),Comparator.reverseOrder()).thenComparing(r->String.valueOf(r.get("logRef")))).limit(wanted).map(r->redaction.redact(r,personal)).toList();}
  private void validate(Search r){if(r.from()==null||r.to()==null||!r.from().isBefore(r.to()))throw invalid("THS_LOG_INTERVAL_INVALID","A valid half-open time interval is required");if(Duration.between(r.from(),r.to()).compareTo(MAX_WINDOW)>0)throw invalid("THS_LOG_INTERVAL_TOO_LARGE","Log search interval cannot exceed 31 days");if(limit(r)<1||limit(r)>MAX_RESULTS)throw invalid("THS_LOG_RESULT_CAP_INVALID","Result limit must be between 1 and 200");}
  private void authorize(OnboardingService.Actor actor,String capability,String purpose,String auth,String op,Map<String,Object> scope,String correlation){try{guard.require(actor,capability,purpose,auth);}catch(DomainFailure failure){audit(actor,op,purpose==null?"unspecified":purpose,scope,0,auth==null?"unavailable":auth,"DENIED",correlation);throw failure;}}
  private void audit(OnboardingService.Actor actor,String op,String purpose,Map<String,Object> scope,int count,String auth,String outcome,String correlation){db.sql("insert into ouf_onboarding.protected_log_access_audit(access_id,actor_subject,operation,purpose,request_scope,result_count,authorization_context_ref,outcome,correlation_id) values(:i,:a,:o,:p,cast(:s as jsonb),:n,:x,:u,:c)").param("i",UUID.randomUUID()).param("a",actor.subject()).param("o",op).param("p",purpose).param("s",write(redaction.redact(scope,false))).param("n",count).param("x",auth).param("u",outcome).param("c",correlation).update();}
  private Map<String,Object> exportForActor(UUID id,OnboardingService.Actor actor){Map<String,Object> row=rawExport(id);if(!actor.subject().equals(row.get("requested_by"))&&!actor.capabilities().contains("ouf.ths.log.export.read.any"))throw new DomainFailure(HttpStatus.FORBIDDEN,"THS_LOG_EXPORT_OWNER_REQUIRED","Export belongs to another operator");Map<String,Object> out=new LinkedHashMap<>(row);out.remove("artifact");out.remove("authorization_context_ref");out.remove("request_scope");return out;}
  private Map<String,Object> export(UUID id){Map<String,Object> out=new LinkedHashMap<>(rawExport(id));out.remove("artifact");out.remove("authorization_context_ref");return out;}
  private Map<String,Object> rawExport(UUID id){Map<String,Object> row=db.sql("select export_id,requested_by,purpose,authorization_context_ref,request_scope::text request_scope,state,attempts,record_count,result_ref,checksum,artifact::text artifact,expires_at,error_code,created_at,updated_at,completed_at from ouf_onboarding.protected_log_export_job where export_id=:i").param("i",id).query().listOfRows().stream().findFirst().orElseThrow(()->new DomainFailure(HttpStatus.NOT_FOUND,"THS_LOG_EXPORT_NOT_FOUND","Protected log export not found"));Map<String,Object> out=new LinkedHashMap<>(row);if(out.get("request_scope")!=null)out.put("request_scope",readMap(out.get("request_scope")));return out;}
  private Map<String,Object> scope(Search r){Map<String,Object> out=new LinkedHashMap<>();out.put("from",r.from());out.put("to",r.to());put(out,"service",r.service());put(out,"severity",r.severity());put(out,"correlationId",r.correlationId());put(out,"eventType",r.eventType());out.put("limit",limit(r));return out;}
  private Search fromScope(Map<String,Object> s,String purpose){return new Search(OffsetDateTime.parse(String.valueOf(s.get("from"))),OffsetDateTime.parse(String.valueOf(s.get("to"))),string(s,"service"),string(s,"severity"),string(s,"correlationId"),string(s,"eventType"),((Number)s.getOrDefault("limit",MAX_RESULTS)).intValue(),null,purpose);}
  private Map<String,Object> readMap(Object value){try{return json.readValue(String.valueOf(value),new TypeReference<>(){});}catch(Exception e){throw new IllegalStateException("invalid persisted JSON",e);}}
  private String write(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalArgumentException(e);}}
  private static void put(Map<String,Object> map,String key,String value){if(value!=null&&!value.isBlank())map.put(key,value);}
  private static String string(Map<String,Object> map,String key){Object value=map.get(key);return value==null?null:String.valueOf(value);}
  private static String blank(String value){return value==null||value.isBlank()?null:value;}
  private static String safe(String value){return value==null?"":value.length()>500?value.substring(0,500):value;}
  private static int limit(Search r){return r.limit()==null?50:r.limit();}
  private static String cursor(Map<String,Object> row){return Base64.getUrlEncoder().withoutPadding().encodeToString(String.valueOf(row.get("timestamp")).getBytes(StandardCharsets.UTF_8));}
  private static Optional<OffsetDateTime> cursorTime(String cursor){try{return cursor==null||cursor.isBlank()?Optional.empty():Optional.of(OffsetDateTime.parse(new String(Base64.getUrlDecoder().decode(cursor),StandardCharsets.UTF_8)));}catch(Exception e){throw invalid("THS_LOG_CURSOR_INVALID","Invalid pagination cursor");}}
  private static OffsetDateTime utc(Instant value){return OffsetDateTime.ofInstant(value,ZoneOffset.UTC);}
  private static DomainFailure invalid(String code,String message){return new DomainFailure(HttpStatus.UNPROCESSABLE_ENTITY,code,message);}
}
